apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: delvex-cluster-new
  region: us-east-1
  version: "1.29"
  
nodeGroups:
  - name: ec2-nodegroup1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 80
    volumeType: gp2
    minSize: 2
    maxSize: 8


fargateProfiles:
  - name: ashu-profile1
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default-ashu
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-ashu
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: dev
        labels:
          env: dev
          checks: passed
    tags:
      env: dev
      name: fp-dev

availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']